// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7KsU-eySXh-PI09Y4c8cRkrJRvKY7kg',
    appId: '1:312436092339:android:4330f488752369765eafc6',
    messagingSenderId: '312436092339',
    projectId: 'sanp-cart',
    storageBucket: 'sanp-cart.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWqvJKs0T7Pn2iEtK4DySKGUIoSXK5I4U',
    appId: '1:312436092339:ios:9f025815177957f95eafc6',
    messagingSenderId: '312436092339',
    projectId: 'sanp-cart',
    storageBucket: 'sanp-cart.firebasestorage.app',
    iosBundleId: 'com.example.snapKartAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6se_Vt535lSmtNhGhGu_86dqZ7FF1WYI',
    appId: '1:312436092339:web:bf82aba5f81d21d95eafc6',
    messagingSenderId: '312436092339',
    projectId: 'sanp-cart',
    authDomain: 'sanp-cart.firebaseapp.com',
    storageBucket: 'sanp-cart.firebasestorage.app',
    measurementId: 'G-47PT8VX4LT',
  );
}
